### ISSUE TITLE
Initial setup

### ISSUE THREAD

**Issue by detlefarend** [fhswf/MLPro-Int-River#1]
**Description/Motivation**
After relocating the related wrapper and howto code the following steps are required.

**Task list**
- [x] 1. Setup workflow ci.yml
- [x] 2. Integration RTD
- [x] 3. Completion of RTD
   - [x] Welcome page
   - [x] API
   - [x] Howtos 
   - [x] About
- [x] 4. New issue label 'next release' 
- [x] 5. [Integration PyPI](https://packaging.python.org/en/latest/tutorials/packaging-projects/)
- [ ] 6. Integration Conda
- [x] 7. Pre-Release v0.1.0
- [x] 8. Integration MLPro extension hub (follow steps in auto-generated issue)
